第二次考核复盘

# linux的权限



## linux文件权限



## linux进程权限



## linux 用户权限



# docker



# linux输出

command（命令） >xxx.txt   2>&1

文件描述符

0：标准输入

1：标准输出

2：标准错误

2>：标准错误输出

2>&1：标准错误输出和标准输出

command > xxx.txt将文件描述符对应的内容重定向到一个文件中，实现保存标准输出和标准错误输出



# nginx和uwsgi配置2

[Django + Uwsgi + Nginx 的生产环境部署 - 云+社区 - 腾讯云 (tencent.com)](https://cloud.tencent.com/developer/article/1594840)

```bash
[uwsgi]
http-socket = 0.0.0.0:9100
#http-socket = 127.0.0.1:9100
#plugin = python
#根目录
chdir = /root/code_plat/ 
#project的wsgi文件
wsgi-file = code_plat/wsgi.py
#master 进程可以存在
master = True
#四个worker进程（两个线程）
processes = 4
threads = 2
#移除unix socket和pid，如果停止服务
vacuum = True
#将接受的内容序列化
thunder-lock = True
#统计信息访问,先放在内网上
#stats = 127.0.0.1:9001
#放到文件中
stats = %(chdir)uwsgi/uwsgi.stats
#将日志输出，使得进程可以在后台运行
daemonize = %(chdir)uwsgi/uwsgi.log
#控制日志的大小,500m够了
log-maxsize = 500000
#日志中有如果有大量200文件非常恐怖，我们只关心错误的请求
#disable-logging = True
#指定pid文件的位置，记录主进程的pid号
pidfile = %(chdir)uwsgi/uwsgi.pid

```

![image-20210617223239459](https://raw.githubusercontent.com/whr819987540/pic/main/image-20210617223239459.png)

```bash
[nginx]#
server {
    listen    9998;#这个是说nginx开启的端口号
    server_name 47.105.91.99;#服务器的公网ip，做测试的时候就是localhost
    charset     utf-8;

    root /var/www;

    location /static {
        expires 30d;
    }
       location /code_plat {#nginx对怎样的url pattern进行相应，这个就是以/code_plat结尾的url
        include uwsgi_params;
        uwsgi_pass 127.0.0.1:9000;#通过本机（127.0.0.1的那个端口转发给uWSGI服务器
        uwsgi_read_timeout 2;  
}
}

```



# python读取cmd输出

## 命令执行没有问题

```python
import os
r=os.popen("dir")
print(r.read())
```



![image-20210617223700978](https://gitee.com/hit_whr/pic_3.0/raw/master/img/image-20210617223700978.png)

## 命令执行出错

```python
import os
r=os.popen("python run.py")
text=r.read()
text=text.encode("utf-8")
text=text.decode("utf-8",errors="ignore")
print(text)
print("333")
for i in range(10):
    print(i)
```

```python
run.py
print("hello")
print(1/0)
```

这样还是会引发异常，在os.popen后面再套一层

```python
import os
try:
    r=os.popen("python run.py")
except:
    print("error")
else:
    text=r.read()
    text=text.encode("utf-8")
    text=text.decode("utf-8",errors="ignore")
    print(text)
print("333")
for i in range(10):
    print(i)

```

![](https://gitee.com/hit_whr/pic_3.0/raw/master/img/image-20210617225251591.png)

还是引发异常，为啥呢？因为os.popen()确实没有问题，命令本身没有问题。否则，换成一个错误命令

![image-20211024133740980](https://raw.githubusercontent.com/whr819987540/pic/main/image-20211024133740980.png)



所以，如果要执行一段py代码，应该对标准输出进行重定向

```python
import os
try:
    r=os.popen("python run.py >res.txt")
except:
    print("error")
else:
    text=r.read()
    text=text.encode("utf-8")
    text=text.decode("utf-8",errors="ignore")
    print(text)
print("333")
```

如果程序是正确的，这样写没问题

![image-20210617225727563](https://gitee.com/hit_whr/pic_3.0/raw/master/img/image-20210617225727563.png)



![image-20211024133728616](https://raw.githubusercontent.com/whr819987540/pic/main/image-20211024133728616.png)



如果run.py有问题，这样写还是报错

![image-20210617225814153](https://gitee.com/hit_whr/pic_3.0/raw/master/img/image-20210617225814153.png)



![image-20211024133716089](https://raw.githubusercontent.com/whr819987540/pic/main/image-20211024133716089.png)

因为只对标准输出进行了重定向，而没有对标准错误进行重定向

```python
import os
try:
    r=os.popen("python run.py >res.txt 2>&1")
except:
    print("error")
else:
    text=r.read()
    text=text.encode("utf-8")
    text=text.decode("utf-8",errors="ignore")
    print(text)
print("333")
```

![image-20211024133705104](https://raw.githubusercontent.com/whr819987540/pic/main/image-20211024133705104.png)



![image-20211024133652385](https://raw.githubusercontent.com/whr819987540/pic/main/image-20211024133652385.png)

### 自动模块安装



```python

import traceback,os
signal=1
while(1):
    try:
        #user_code
        import time,os
        print("hello")
        print(1/0)
    except ImportError as e:
        if(signal):
        #import error, try pip only once
            signal=0
            back = e.__str__()
            list = back.split(' ')
            cmd = 'pip install ' + list[-1].strip("'")
            try:
                #after tying to install,still fail,quit trying
                r=os.popen(cmd)
                continue
            except:
                pass
        else:
             print("module not found and no matching distribution")

    other types of error,return erro info
    except:

        text=traceback.format_exc()
        text=text.encode(encoding='utf-8')
        text=text.decode(encoding='utf-8',errors='ignore')
        print("before")
        print(text)
    break
```





# python获取traceback

在try，except模块中，如果引发了异常，可以通过traceback来知道引发异常的具体信息

```python
import traceback
try:
    print("----")
    print(1/0)
    print("====")
except:
    text=traceback.format_exc()
    text=text.encode("utf-8")
    text=text.decode("utf-8",errors="ignore")
    print(text)
D:/pythoncode/云端代码平台/done_traceback/third/my_traceback.py
----
Traceback (most recent call last):
  File "D:/pythoncode/云端代码平台/done_traceback/third/my_traceback.py", line 4, in <module>
    print(1/0)
ZeroDivisionError: division by zero

over
```



如果没有traceback模块，会直接停止程序运行并输出错误信息

```python
print("----")
print(1/0)
print("====")
D:/pythoncode/云端代码平台/done_traceback/third/my_traceback.py
----
Traceback (most recent call last):
  File "D:/pythoncode/云端代码平台/done_traceback/third/my_traceback.py", line 2, in <module>
    print(1/0)
ZeroDivisionError: division by zero
```



# python限制程序执行时间

eventlet模块

```python
import time
import eventlet  # 导入eventlet这个模块

eventlet.monkey_patch()  # 必须加这条代码
with eventlet.Timeout(2, False):  # 设置超时时间为2秒
    a=10
    time.sleep(4)
    a=11
print(a)

10
```



# python的共享变量

```python
[aa.py]
import aaa
def func():
    aaa.str+="2"
```



```python
[aaa.py]
str="222"
if __name__=="__main__":
    print(str)
```



```python
[aaaa.py]
import  aaa,aa
print("====")
print(aaa.str)#222
print("======")
aaa.str+="1"
print(aaa.str)#2221
aa.func()
print(aaa.str)#22212

====
222
======
2221
22212
```

